extern unsigned char code number_0[16];/*"0",0*/

extern unsigned char code number_1[16];/*"1",1*/

extern unsigned char code number_2[16];/*"2",2*/

extern unsigned char code number_3[16];/*"3",3*/

extern unsigned char code number_4[16];/*"4",4*/

extern unsigned char code number_5[16];/*"5",5*/

extern unsigned char code number_6[16];/*"6",6*/

extern unsigned char code number_7[16];/*"7",7*/

extern unsigned char code number_8[16];/*"8",8*/

extern unsigned char code number_9[16];/*"9",9*/

extern unsigned char code number_10[16];/*":",10*/

extern unsigned char code number_11[16];/*"*",11*/

extern unsigned char code number_12[16];/*":",12*/

extern unsigned char code number_13[16];/*" ",13*/


extern unsigned char code chiness_1[32];//"请",1;
extern unsigned char code chiness_2[32];//"再",2;
extern unsigned char code chiness_3[32];//"次",3;
extern unsigned char code chiness_4[32];//"输",4;
extern unsigned char code chiness_5[32];//"入",5;
extern unsigned char code chiness_6[32];//"指",6;
extern unsigned char code chiness_7[32];//"纹",7;
extern unsigned char code chiness_8[32];//"：",8;

extern unsigned char code chiness_9[32];//"欢",9;

extern unsigned char code chiness_10[32];//"迎",10;
extern unsigned char code chiness_11[32];//"使",11;
extern unsigned char code chiness_12[32];//"用",12;
extern unsigned char code chiness_13[32];//"！",13;
extern unsigned char code chiness_14[32];//"新",14;
extern unsigned char code chiness_15[32];//密",15;
extern unsigned char code chiness_16[32];//"码",16;
extern unsigned char code chiness_17[32];//"录",17;
extern unsigned char code chiness_18[32];//"入",18;
extern unsigned char code chiness_19[32];//"验",19;
extern unsigned char code chiness_20[32];//"证",20;
extern unsigned char code chiness_21[32];//"失",21;
extern unsigned char code chiness_22[32];//"败",22;
extern unsigned char code chiness_23[32];//"修",23;
extern unsigned char code chiness_24[32];//"改",24;
extern unsigned char code chiness_25[32];//"成",25;
extern unsigned char code chiness_26[32];//"功",26;
extern unsigned char code chiness_27[32];//"库",27;
extern unsigned char code chiness_28[32];//"已",28;
extern unsigned char code chiness_29[32];//"清",29;
extern unsigned char code chiness_30[32];//"空",30;
extern unsigned char code chiness_31[32];//"恢",31;
extern unsigned char code chiness_32[32];//"复",32;
extern unsigned char code chiness_33[32];//"功",33;
extern unsigned char code chiness_34[32];//"能",34;
extern unsigned char code chiness_35[32];//"取",35;
extern unsigned char code chiness_36[32];//"消",36;
extern unsigned char code chiness_37[32];//"系",37;
extern unsigned char code chiness_38[32];//"统",38;
extern unsigned char code chiness_39[32];//"删",39;
extern unsigned char code chiness_40[32];//"除",40;
extern unsigned char code chiness_41[32];//"号",41;
extern unsigned char code chiness_42[32];//"车",42;
extern unsigned char code chiness_43[32];//"主",43;
extern unsigned char code chiness_44[32];//"已",44;
extern unsigned char code chiness_45[32];//"数",45;
extern unsigned char code chiness_46[32];//"系",46;
extern unsigned char code chiness_47[32];//"统",47;
extern unsigned char code chiness_48[32];//"通",48;
extern unsigned char code chiness_49[32];//"信",49;
extern unsigned char code chiness_50[32];//"正",50;
extern unsigned char code chiness_51[32];//"常",51;
extern unsigned char code chiness_52[32];//"设",52;
extern unsigned char code chiness_53[32];//"置",53;
extern unsigned char code chiness_54[32];//"报",54;
extern unsigned char code chiness_55[32];//"警",55;
extern unsigned char code chiness_56[32];//"手",56;
extern unsigned char code chiness_57[32];//"机",57;
extern unsigned char code chiness_58[32];//"号",58;
extern unsigned char code chiness_59[32];//"无",59;
extern unsigned char code chiness_60[32];//"网",60;
extern unsigned char code chiness_61[32];//"络",61;
extern unsigned char code chiness_62[32];//"检",62;
extern unsigned char code chiness_63[32];//"测",63;
extern unsigned char code chiness_64[32];//"信",64;
extern unsigned char code chiness_65[32];//"号",65;
extern unsigned char code chiness_66[32];//"一",66;
extern unsigned char code chiness_67[32];//"二",67
extern unsigned char code chiness_68[32];//"原",68


extern unsigned char code chiness_69[32];/*"区",69*/

extern unsigned char code chiness_70[32];/*"房",70*/

extern unsigned char code chiness_71[32];/*"床",71*/


extern unsigned char code chiness_72[32];/*"号",72*/

